# Generated by Django 4.1 on 2022-09-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200, null=True)),
                ('seller', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
