# Generated by Django 4.1 on 2022-09-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOLO33', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
